### ISSUE TITLE
Unable to register new account

### ISSUE THREAD

**Issue by schwab** [lakewik/storj-gui-client#103]
New install, attempt to register a user. 

```2018-03-08 14:44:48,060 ERROR Error in Account Manager login
ERROR Error in Account Manager login
2018-03-08 14:44:48,061 ERROR Function: if_logged_in
ERROR Function: if_logged_in
2018-03-08 14:44:48,061 ERROR Credentials file not existing
ERROR Credentials file not existing
2018-03-08 14:44:48,147 ERROR Error in Account Manager login
ERROR Error in Account Manager login
2018-03-08 14:44:48,147 ERROR Function: if_logged_in
ERROR Function: if_logged_in
2018-03-08 14:44:48,147 ERROR Credentials file not existing
ERROR Credentials file not existing
testlogin, StorjEngine
2018-03-08 14:44:48,147 DEBUG testlogin, StorjEngine
DEBUG testlogin, StorjEngine
Traceback (most recent call last):
  File "/mnt/extradrive1/projects/storj-gui-client/UI/registration.py", line 43, in register
    self.storj_client = storj.Client(None, "", api_url=self.bridge_api_url).user_create(str(self.email).strip(), str(self.password).strip())
TypeError: __init__() got an unexpected keyword argument 'api_url'
Traceback (most recent call last):
  File "/mnt/extradrive1/projects/storj-gui-client/UI/registration.py", line 43, in register
    self.storj_client = storj.Client(None, "", api_url=self.bridge_api_url).user_create(str(self.email).strip(), str(self.password).strip())
TypeError: __init__() got an unexpected keyword argument 'api_url'

```

**Comment by marcorosa** [comment]
are you building from source or are you using one of the releases?

**Comment by schwab** [comment]
yes, I pulled from source and did the setup. 
Fixed it with this, the api_url field is NLA:

 `   self.storj_client = storj.Client(None, "", storj_bridge=self.bridge_api_url).user_create(str(self.email).strip(), str(self.password).strip())`

**Comment by marcorosa** [comment]
If you use source, your problem should have been addressed [here](https://github.com/lakewik/EasyStorj/commit/3afa5df6472b83d92bfcbd60f82c3ac831474856#diff-abe8cf65f15819478d31b87e72676062R44)
Please pull the latest version of the code and verify if the registration is still broken
