### ISSUE TITLE
file_download.py: NoneType has no attribute id

### ISSUE THREAD

**Issue by steenzout** [lakewik/storj-gui-client#19]
```
03-16T23;38;55.761Z)-32.jpg', u'id': u'07875ae819bfce75baf52bc8', u'size': 220525}
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QHeaderView(0x4f28c18), parent's thread is QThread(0x29a8638), current thread is QThread(0x5256f80)
QObject::startTimer: timers cannot be started from another thread
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QHeaderView(0x4f290d8), parent's thread is QThread(0x29a8638), current thread is QThread(0x5256f80)
QObject::startTimer: timers cannot be started from another thread
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QTableView(0x4f09578), parent's thread is QThread(0x29a8638), current thread is QThread(0x5256f80)
QObject::startTimer: timers cannot be started from another thread
Exception in thread Thread-10:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "storj-gui-client\UI\file_download.py", line 394, in download_begin
  File "storj-gui-client\UI\file_download.py", line 590, in get_file_pointers_count
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by steenzout** [comment]
related to #27 ...

**Comment by steenzout** [comment]
closing this issue in favor of the other.

**Comment by lakewik** [comment]
This file is uploaded by CLI?

**Comment by steenzout** [comment]
@MeijeSibbel ^
