### ISSUE TITLE
Joining shards not working due to `Access is denied`

### ISSUE THREAD

**Issue by MeijeSibbel** [lakewik/storj-gui-client#22]
``` 
nowe wskazniki"title": "Shard downloaded"

2017-04-28 03:03:22,654 DEBUG "title": "Shard downloaded"
"description": "Shard at index "1 downloaded successfully.
2017-04-28 03:03:22,661 DEBUG "description": "Shard at index "1 downloaded successfully.
konczenie downloadu
"title": "Sharding"
2017-04-28 03:03:22,670 DEBUG "title": "Sharding"
"description": "Joining shards..."
2017-04-28 03:03:22,674 DEBUG "description": "Joining shards..."
Traceback (most recent call last):
  File "logging\__init__.py", line 861, in emit
  File "logging\__init__.py", line 734, in format
  File "logging\__init__.py", line 465, in format
  File "logging\__init__.py", line 329, in getMessage
TypeError: not all arguments converted during string formatting
Logged from file sharder.py, line 83
Traceback (most recent call last):
  File "logging\__init__.py", line 861, in emit
  File "logging\__init__.py", line 734, in format
  File "logging\__init__.py", line 465, in format
  File "logging\__init__.py", line 329, in getMessage
TypeError: not all arguments converted during string formatting
Logged from file sharder.py, line 83
Traceback (most recent call last):
  File "storj-gui-client\UI\file_download.py", line 102, in <lambda>
  File "storj-gui-client\UI\file_download.py", line 263, in create_download_finish_thread
  File "storj-gui-client\UI\file_download.py", line 287, in finish_download
  File "storj-gui-client\UI\utilities\sharder.py", line 101, in join_shards
WindowsError: [Error 5] Access is denied: 'C:\\Windows\\temp/*.*'
```
- Download hangs, if i change the temp directory it work fine.

**Comment by MeijeSibbel** [comment]
If this is an error of just my system let me know and i will close the issue (or do it for me)
