### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by MeijeSibbel** [lakewik/storj-gui-client#27]
```
2017-04-28 03:27:13,262 INFO Row 3 is selected
zpliku d894cfc6ee576b33b56f4467eac24ca5774245cc580185b895273d90b937aaa1
Login from credentials xml file
2017-04-28 03:27:13,312 DEBUG Login from credentials xml file
testlogin, StorjEngine
2017-04-28 03:27:13,316 DEBUG testlogin, StorjEngine
zpliku d894cfc6ee576b33b56f4467eac24ca5774245cc580185b895273d90b937aaa1
1
2017-04-28 03:27:13,392 DEBUG 1
No handlers could be found for logger "storj.http.Client"
Exception in thread Thread-11:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "storj-gui-client\UI\file_download.py", line 394, in download_begin
  File "storj-gui-client\UI\file_download.py", line 590, in get_file_pointers_count
AttributeError: 'NoneType' object has no attribute 'id'

```
trying to download a random old file uploaded with core-CLI

**Comment by lakewik** [comment]
GUI currently not support downloading files uploaded by cli. It will be fixed

**Comment by lakewik** [comment]
Only happen for files uploaded by CLI?

**Comment by MeijeSibbel** [comment]
yeah

**Comment by lakewik** [comment]
So related to #14
