### ISSUE TITLE
ValueError: Input strings must be a multiple of 16 in length

### ISSUE THREAD

**Issue by MeijeSibbel** [lakewik/storj-gui-client#28]
```
TypeError: not all arguments converted during string formatting
Logged from file sharder.py, line 130
Traceback (most recent call last):
  File "logging\__init__.py", line 861, in emit
  File "logging\__init__.py", line 734, in format
  File "logging\__init__.py", line 465, in format
  File "logging\__init__.py", line 329, in getMessage
TypeError: not all arguments converted during string formatting
Logged from file sharder.py, line 130
C:\Users\Dani Marion\Downloads/fesdf.encrypted
2017-04-28 03:30:56,404 DEBUG C:\Users\Dani Marion\Downloads/fesdf.encrypted
"title": "Decryption"
2017-04-28 03:30:56,411 DEBUG "title": "Decryption"
"description": "Decrypting file..."
2017-04-28 03:30:56,414 DEBUG "description": "Decrypting file..."
Traceback (most recent call last):
  File "storj-gui-client\UI\file_download.py", line 102, in <lambda>
  File "storj-gui-client\UI\file_download.py", line 263, in create_download_finish_thread
  File "storj-gui-client\UI\file_download.py", line 304, in finish_download
  File "storj-gui-client\UI\crypto\file_crypto_tools.py", line 19, in decrypt_file
  File "storj-gui-client\UI\crypto\file_crypto_tools.py", line 51, in decrypt_file_aes
  File "site-packages\Crypto\Cipher\blockalgo.py", line 295, in decrypt
ValueError: Input strings must be a multiple of 16 in length
[]wskaznik
[]wskaznik
[]wskaznik
[]wskaznik
[]wskaznik
[]wskaznik
[]wskaznik
[]wskaznik
[]wskaznik
[]wskaznik
[]wskaznik
[]wskaznik
[]wskaznik
[]wskaznik
[]wskaznik
```
`File: C:/Users/Dani Marion/Downloads/fesdf`
`Temp path: C:\Users\Dani Marion\Downloads`
real file name: `storj .exe`

**Comment by MeijeSibbel** [comment]
Error at download btw^

**Comment by lakewik** [comment]
**Probably** related to #14

**Comment by MeijeSibbel** [comment]
To be implemented.
