### ISSUE TITLE
Does not display buckets with non-ASCII characters in names

### ISSUE THREAD

**Issue by AlexeyALeonov** [lakewik/storj-gui-client#38]
After successful login i get the Exception in terminal window:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "storj-gui-client\UI\mainUI.py", line 216, in initialize_bucket_select_combobox
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "storj-gui-client\UI\mainUI.py", line 174, in update_files_list
IndexError: list index out of range
```

**Comment by AlexeyALeonov** [comment]
main-newest is running and work some way :)
![default](https://cloud.githubusercontent.com/assets/26858949/25547205/c55c62a2-2c6e-11e7-8654-531ea82f3c9e.png)

**Comment by lakewik** [comment]
Yes, some progress, but still unfisished, probably tomorrow will be done :) Also please check bucket select list in file upload dialog - there should be good, but please give me a feedback

**Comment by AlexeyALeonov** [comment]
nope, is not good :)
![image](https://cloud.githubusercontent.com/assets/26858949/25547323/42f22d50-2c6f-11e7-99e5-525c7c315f36.png)

**Comment by lakewik** [comment]
Oh, strange, so It probably will be fixed tomorrow :) Thanks for reporting :)

**Comment by AlexeyALeonov** [comment]
You're welcome

**Comment by lakewik** [comment]
Fixed in branch develop, binaries will be soon

**Comment by AlexeyALeonov** [comment]
now it's showing :)
