### ISSUE TITLE
Does not allow uploading files with non-ASCII characters in the path

### ISSUE THREAD

**Issue by AlexeyALeonov** [lakewik/storj-gui-client#43]
I'm trying to upload the file from directory with non-ASCII characters in the path and getting exception:
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "storj-gui-client\UI\file_upload.py", line 809, in file_upload_begin
  File "storj-gui-client\UI\crypto\file_crypto_tools.py", line 13, in encrypt_file
IOError: [Errno 2] No such file or directory: 'Y:/Photo/2004.08.07, \xd0\x91\xd0\xbe\xd0\xb4\xd0\xb8\xd0\xb0\xd1\x80\xd1\x82-\xd0\x90\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb0/\xd0\x91\xd0\xbe\xd0\xb4\xd0\xb8\xd0\xb0\xd1\x80\xd1\x82-\xd0\x90\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb0.avi'
```

**Comment by lakewik** [comment]
Fixed in branch davelop, Windows binaries soon

**Comment by AlexeyALeonov** [comment]
working now
