### ISSUE TITLE
Uploads of large files hangs at `Splitting file to shards`

### ISSUE THREAD

**Issue by MeijeSibbel** [lakewik/storj-gui-client#49]
```
QPixmap: It is not safe to use pixmaps outside the GUI thread
Exception in thread Thread-195:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "storj-gui-client\UI\file_upload.py", line 916, in file_upload_begin
  File "site-packages\storj\model.py", line 692, in __init__
  File "site-packages\storj\model.py", line 710, in filepath
  File "site-packages\storj\model.py", line 834, in _make_shards
OverflowError: Python int too large to convert to C long

Exception in thread Thread-192:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "storj-gui-client\UI\file_upload.py", line 916, in file_upload_begin
  File "site-packages\storj\model.py", line 692, in __init__
  File "site-packages\storj\model.py", line 710, in filepath
  File "site-packages\storj\model.py", line 834, in _make_shards
OverflowError: Python int too large to convert to C long
``` 

- upload of a 43GB file on windows 8.1.

**Comment by lakewik** [comment]
Should be fixed in uploads, if not please reopen

**Comment by GrolaG** [comment]
Uploads of large files hangs at `Splitting file to shards`.
Atom C2750 CPU, 2 or 8 GiB RAM, Ubuntu 16.10
With 2 GiB ram can't upload file with ~1GiB shard (with 8 all ok up to 3GiB/shard)
