### ISSUE TITLE
MemoryError at download

### ISSUE THREAD

**Issue by MeijeSibbel** [lakewik/storj-gui-client#60]
```
TypeError: not all arguments converted during string formatting
Logged from file sharder.py, line 116
D:\downloaded/libgen.scimag00200000-00200999.zip-16katalog wejsciowy
2017-04-30 23:03:47,230 INFO D:\downloaded/libgen.scimag00200000-00200999.zip-16katalog wejsciowy
Traceback (most recent call last):
  File "logging\__init__.py", line 861, in emit
  File "logging\__init__.py", line 734, in format
  File "logging\__init__.py", line 465, in format
  File "logging\__init__.py", line 329, in getMessage
TypeError: not all arguments converted during string formatting
Logged from file sharder.py, line 116
Traceback (most recent call last):
  File "logging\__init__.py", line 861, in emit
  File "logging\__init__.py", line 734, in format
  File "logging\__init__.py", line 465, in format
  File "logging\__init__.py", line 329, in getMessage
TypeError: not all arguments converted during string formatting
Logged from file sharder.py, line 116
Traceback (most recent call last):
  File "storj-gui-client\UI\file_download.py", line 103, in <lambda>
  File "storj-gui-client\UI\file_download.py", line 306, in create_download_finish_thread
  File "storj-gui-client\UI\file_download.py", line 330, in finish_download
  File "storj-gui-client\UI\utilities\sharder.py", line 117, in join_shards
MemoryError
```
700MB file
windows 8.1
PC has 2GB RAM

**Comment by MeijeSibbel** [comment]
Total download proces hangs at 97%, single shard download hangs at 40%

**Comment by lakewik** [comment]
@MeijeSibbel You can reproduce this error? Can you check on other machine?

**Comment by steenzout** [comment]
my previous attempts at fixing this failed miserably.
I need to get the GUI working on mac and then to test this locally.

**Comment by steenzout** [comment]
related to https://github.com/Storj/storj-python-sdk/issues/109

**Comment by lakewik** [comment]
https://github.com/lakewik/storj-gui-client/blob/develop/UI/utilities/sharder.py#L80
