### ISSUE TITLE
Uploads of large files hangs at Splitting file to shards.

### ISSUE THREAD

**Issue by GrolaG** [lakewik/storj-gui-client#97]
Atom C2750 CPU, 2 or 8 GiB RAM, Ubuntu 16.10, using `storj-gui-client-v0.1.9.2-linux`.
With 2 GiB ram can't upload file with ~1GiB shard (with 8GiB RAM all ok up to 3GiB/shard)

**Comment by schwab** [comment]
I got the same issue with just an 8.0MB file.  Stuck on "Splitting file to shares" for hours now.
Edit: just found this in the logs regarding the hung splitting file to shares... 
`EBUG Splitting file to shards...
4194304 max shard size
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/mnt/extradrive1/projects/storj-gui-client/UI/file_upload.py", line 1288, in file_upload_begin
    max_shard_size=int(max_shard_size_setting)/2)
TypeError: __init__() got an unexpected keyword argument 'max_shard_size'
`

simply removing the max_shard_size setting fixes the issue and allows the files upload.
```
      shards_manager = storj.model.ShardManager(filepath=file_path_ready,
                                                      tmp_path=self.tmp_path)
                                                      #,max_shard_size=int(max_shard_size_setting)/2)
```
